import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const app = read('apps/desktop/renderer/src/App.jsx')
const foundation = read('apps/desktop/renderer/src/ui-foundation.mjs')
const foundationCss = read('apps/desktop/renderer/src/ui-foundation.css')
const glassCss = read('apps/desktop/renderer/src/glass.css')
const main = read('apps/desktop/electron/main.mjs')
const preload = read('apps/desktop/electron/preload.mjs')
const mainEntry = read('apps/desktop/renderer/src/main.jsx')

test('desktop background personalization uses a dedicated secure Electron boundary', () => {
  assert.match(preload, /chooseDesktopBackground: \(\) => ipcRenderer\.invoke\('personalOS:appearance:chooseDesktopBackground'\)/)
  assert.match(preload, /resetDesktopBackground: \(\) => ipcRenderer\.invoke\('personalOS:appearance:resetDesktopBackground'\)/)
  assert.doesNotMatch(preload, /readFile|writeFile|readdir|require\(['"]node:fs/)
  assert.match(main, /dialog\.showOpenDialog\(/)
  assert.match(main, /extensions: \['png', 'jpg', 'jpeg', 'webp'\]/)
  assert.match(main, /appearance-assets/)
  assert.match(main, /copyFileSync\(/)
  assert.match(main, /yren-appearance/)
  assert.match(main, /registerAppearanceAssetProtocol/)
  assert.match(main, /personalOS:appearance:chooseDesktopBackground/)
  assert.match(main, /personalOS:appearance:resetDesktopBackground/)
})

test('desktop background and UI Scale are bound to the existing appearance and Foundation paths', () => {
  assert.match(app, /applyDesktopBackground\(appearance\)/)
  assert.match(app, /appearance\.desktopBackground\?\.kind === 'custom'/)
  assert.match(app, /yren-appearance:\/\/appearance\//)
  assert.match(app, /id="ui-scale-slider"/)
  assert.match(app, /uiScaleProfile/)
  assert.match(app, /ui-scale-\$\{axis\}-slider/)
  assert.match(app, /\['typography', 'settings\.uiTypographyScale'/)
  assert.match(app, /\['width', 'settings\.uiWidthScale'/)
  assert.match(app, /\['height', 'settings\.uiHeightScale'/)
  assert.doesNotMatch(app, /uiVerticalSpacingScale|uiHorizontalSpacingScale/)
  assert.match(app, /uiContainerSizes/)
  assert.match(app, /layoutId=/)
  assert.match(app, /uiLayoutPresets/)
  assert.match(app, /saveLayoutPreset/)
  assert.match(app, /resizeBounds\(id, liveSizes/)
  assert.match(app, /measureDefaultSize\(id\)/)
  assert.match(app, /--ui-shell-sidebar-width/)
  assert.match(app, /--ui-shell-min-content-width/)
  assert.match(app, /computedGap\(parentStyle, 'width'\)/)
  assert.match(app, /parentStyle\.height === 'auto'/)
  assert.match(app, /resizable=\{id === 'main-ai'\}/)
  assert.match(app, /resizeEdges="left-bottom"/)
  assert.match(app, /global-panel-main-ai/)
  assert.match(app, /contentMin = cssPixels\(shellStyle\?\.getPropertyValue\('--ui-shell-min-content-width'\)/)
  assert.match(app, /parent\.classList\.contains\('settings-groups'\)/)
  assert.match(app, /parent\.style\.width = `\$\{Math\.max\(\.\.\.customWidths\.filter\(Boolean\)\)\}px`/)
  assert.match(app, /gridTemplateColumns = customWidths/)
  assert.match(app, /maxWidth: 'none'/)
  assert.match(glassCss, /scrollbar-width: none/)
  assert.match(app, /Math\.max\(bounds\.minWidth, bounds\.maxWidth\)/)
  assert.match(app, /appearance\.update\(patch\)/)
  assert.match(app, /api\(\)\.appearance\.chooseDesktopBackground\(\)/)
  assert.match(app, /api\(\)\.appearance\.resetDesktopBackground\(\)/)
  assert.match(foundation, /uiScaleProfile = normalizeUiScaleProfile\(/)
  assert.match(foundation, /--ui-scale-percent/)
  assert.match(foundationCss, /\.desktop-background-preview/)
  assert.match(foundationCss, /--ui-scale/)
  assert.match(glassCss, /data-desktop-background='custom'/)
  assert.match(mainEntry, /default-woven-light\.png/)
  assert.match(mainEntry, /default-woven-dark\.png/)
  assert.match(glassCss, /data-layer="window-environment"|app-window-background/)
})

test('appearance presets expose default and custom persistence controls', () => {
  assert.match(app, /appearancePreset/)
  assert.match(app, /restoreAppearanceDefaults/)
  assert.match(app, /saveCustomAppearance/)
  assert.match(app, /glassStrengthDefault/)
  assert.match(app, /UI_SCALE_PROFILE_DEFAULTS/)
})

test('legacy background asset reference has been fully removed', () => {
  const rendererFiles = [app, foundation, foundationCss, glassCss, mainEntry]
  assert.equal(rendererFiles.filter((source) => source.includes('ChatGPT Image 2026')).length, 0)
})
